### ISSUE TITLE
Brute-force does not work with list of domains.

### ISSUE THREAD

**Issue by vipinbihari** [projectdiscovery/shuffledns#42] opened 2020-08-19 04:59 UTC
`shuffledns -d example.com -r /dnsfinder/resolver.txt -silent -w words.txt -list sub.example.com.txt`
If we run the above command, only the subdomains in sub.example.com.txt are resolved, but the example.com is not 
bruteforced with words.txt wordlist.
In sort,` -w` and `-list` flag can not be used together.

**Comment by bauthard** [comment] 2020-08-19 05:03
Hi @vipinbihari, 

that's right, in the readme, it says:- 

> `shuffledns` supports two types of operations.

1. Bruteforce (works with `-w`)
2. Resolve (works with `-list`)

Can you clarify the purpose of this issue?

**Comment by vipinbihari** [comment] 2020-08-19 05:23
I wanted to use both on the options in a single command.
I have a huge list of subdomain that I want to resolve i.e sub.example.com.txt,
and at the same time, I want to bruteforce  the parent domain (example.com) with a wordlist words.txt.
I want these two operation to be carried out simultaneously.
So my final command becomes.
`shuffledns -d example.com -r /dnsfinder/resolver.txt -silent -w words.txt -list sub.example.com.txt`

**Comment by bauthard** [comment] 2020-08-19 05:50
Hey! 

Unfortunately, that's not possible and not the intended way to use it, you can perform one operation at a time, we might add input validation in the future. 

Closing this issue as this is expected behavior.

**Closed by bauthard** 2020-08-19 05:50 UTC
