### ISSUE TITLE
Filtering bad results not working as expected

### ISSUE THREAD

**Issue by plenumlab** [projectdiscovery/shuffledns#40] opened 2020-08-13 09:55 UTC
Hello,

I just ran shuffle dns on hackerone.com with massdns default resolvers list, i got 655 results, i m using a custom wordlist with 2178753 entries.

I ran the same config with massdns using my bash script and i am able to get only valid domains, i do the clean up separately like follows 
`cat mass.txt | awk '{print $3}' | sort -u | while read line; do valid=$(cat mass.txt | grep -m 1 $line);echo "$valid" ;done` 
if you run this on your machine you should be able to get only valid domains

**Comment by bauthard** [comment] 2020-08-13 10:36
Hey @plenumlab, 

> massdns default resolvers list

This is the root cause, to use `massdns` you need to maintain your own "GOOD" resolver list, otherwise you going to get results like this, check massdns project with multiple issues related to same, and this is something on the users, massdns works as expected if you feed good resolvers. 

Few projects to get and validate the list https://github.com/vortexau/dnsvalidator, closing this issue as it's not an issue with the tool.

**Closed by bauthard** 2020-08-13 10:36 UTC
