### ISSUE TITLE
MassDNS error could not execute massdns: exit status 1

### ISSUE THREAD

**Issue by MMrhassel** [projectdiscovery/shuffledns#7] opened 2020-03-01 16:31 UTC
[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Started generating bruteforce permutation
[INF] Generating permutations took 28.898107ms
[INF] Creating temporary massdns output file: /tmp/shuffledns365027544/bpdu67p92jhup178risg
[INF] Executing massdns on hackerone.com
[ERR] Could not run massdns: could not execute massdns: exit status 1
[INF] Finished resolving. Hack the Planet!

Massdns in : /usr/local/bin/massdns

**Comment by bauthard** [comment] 2020-03-01 17:12
Hi @MMrhassel, 

Can you please share the output of 

```
/usr/local/bin/massdns -h
```

**Comment by dd404x** [comment] 2020-03-05 14:00
![image](https://user-images.githubusercontent.com/19923974/75988564-c0703400-5f2c-11ea-987b-d720c57148b7.png)

**Comment by bauthard** [comment] 2020-03-05 15:01
Hi @dd404x, 

Thank you for adding details on this, we will try to find the root cause, meanwhile, can you confirm if manually providing the `massdns` path works for you? 

For example:- 

```
shuffledns -r resolvers.txt -w words.txt -d test.com -massdns /usr/local/massdns
```

**Comment by dd404x** [comment] 2020-03-06 01:08
![image](https://user-images.githubusercontent.com/19923974/76040246-d5c77b80-5f89-11ea-91fe-2b5d0a37d42b.png)
no problem with the location of masscan

**Comment by dd404x** [comment] 2020-03-07 00:35
My system info：Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-52-generic x86_64)
When I use massdns, he always looks idle

**Comment by dd404x** [comment] 2020-03-07 00:37
![image](https://user-images.githubusercontent.com/19923974/76132588-a29af000-604e-11ea-9624-05852574f3a4.png)
Except that time is increasing, it has always been this state

I tried massdns0.2 and massdns 0.3

**Comment by bauthard** [comment] 2020-03-07 17:51
@MMrhassel this should be fixed with https://github.com/projectdiscovery/shuffledns/pull/10, Can you update the `shuffledns` and try again?

**Comment by proabiral** [comment] 2020-03-09 05:52
@bauthard ,
I am facing the same issue even on the latest shuffledns.

![Screenshot from 2020-03-09 11-33-01](https://user-images.githubusercontent.com/22173232/76186262-e41bce80-61f9-11ea-9606-b3655fda3c6f.png)

**Comment by bauthard** [comment] 2020-03-09 16:19
@proabiral sure, will ping on this.

**Comment by Ice3man543** [comment] 2020-03-09 23:15
@MMrhassel @proabiral @dd404x can you all please download the latest release. It contains detailed error message in case of failure from massdns, which should help us isolate the problem. Thanks a lot!

**Comment by proabiral** [comment] 2020-03-10 02:10
Hi @Ice3man543 @bauthard ,
Seems like I was getting error as massdns is not being allowed to be run as root user from shuffledns.

![Screenshot from 2020-03-10 07-50-22](https://user-images.githubusercontent.com/22173232/76272670-1f72d780-62a4-11ea-9448-3eec9ba44756.png)

Switching to other user solved the issue : 
![Screenshot from 2020-03-10 07-50-35](https://user-images.githubusercontent.com/22173232/76272757-47623b00-62a4-11ea-9256-691a57867634.png)

May be a command line switch for shuffledns that helps to run massdns as root would be helpful :)

Thank you so much for such a quick help :)

**Comment by bauthard** [comment] 2020-03-10 02:39
Thank you for the confirmation @proabiral

**Comment by bauthard** [comment] 2020-03-10 19:36
Closing this out as we identified that `massdns` was getting failed due to permission issues and added more detailed error for any other issues.

**Closed by bauthard** 2020-03-10 19:36 UTC
Labels: bug, need more info

**Comment by proabiral** [comment] 2020-03-12 08:19
@Ice3man543 @bauthard ,
I can try to send pull request for this if you want. :)

**Comment by kvst3ja** [comment] 2020-04-02 15:25
How do i do this in kali linux. how to run massdns as root

**Comment by H3ssam13** [comment] 2023-07-22 14:30
run shuffledns this error 

Could not run massdns: blank input file specified
